routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

//Administrator access
Route::middleware(['checkAuth'])->group(function () {
    Route::resource('user', 'UserController');
    Route::resource('listing', 'ListingController');
});

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Listing extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'list_name', 'address', 'latitude', 'longitude', 'submitter_id'
    ];

    public function submitter()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/API/ListingController.php
<?php

namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;

use App\Listing;

class ListingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getList()
    {
        $user_id = Input::get('user_id');
        $clientlatitude = Input::get('latitude');
        $clientlongitude = Input::get('longitude');
        //Filter listing by requested user_id
        $listing = Listing::where('submitter_id', $user_id)->get();
        $listingdistance = [];

        foreach($listing as $l)
        {
            //Calculate distance between current mobile location and listing location
            $listinglatitude = $l->latitude;
            $listinglongitude = $l->longitude;
            $theta = $clientlongitude - $listinglongitude;
            $distance = sin(deg2rad($clientlatitude)) * sin(deg2rad($listinglatitude)) +  cos(deg2rad($clientlatitude)) * cos(deg2rad($listinglatitude)) * cos(deg2rad($theta));
            $distance = acos($distance);
            $distance = rad2deg($distance);
            //Convert distance to km
            $distanceinkm = $distance * 60 * 1.1515 * 1.609344;
            //Round distance to 3 decimal points
            $distanceinkm = number_format($distanceinkm, 3, '.', '');

            $listingdistance[] = [
                'id' => $l->id,
                'list_name' => $l->list_name,
                'distance' => $distanceinkm
            ];
        }

        return response()->json([
            'listing' => $listingdistance,
            'status' => [
                'code' => 200,
                'message' => 'Listing successfully retrieved'
            ]
        ]);
    }

}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use App\Listing;
use Illuminate\Http\Request;

class ListingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listing = Listing::orderBy('created_at')->paginate(10);
        return view('listing.index', compact('listing'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('listing.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'list_name' => ['required', 'string', 'max:80'],
            'address' => ['required', 'string', 'max:255'],
            'latitude' => ['required', 'numeric', 'between:-90,90'],//Latitude : max/min +90 to -90
            'longitude' => ['required', 'numeric', 'between:-180,180'],//Longitude : max/min +180 to -180
        ]);

        Listing::create([
            'list_name' => $request['list_name'],
            'address' => $request['address'],
            'latitude' => $request['latitude'],
            'longitude' => $request['longitude'],
            'submitter_id' => auth()->user()->id,//Assign admin user_id
        ]);

        return redirect()->route('listing.index')->with('success', 'Listing created successfully.');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $listing = Listing::find($id);
        return view('listing.edit', compact('listing'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'list_name' => ['required', 'string', 'max:80'],
            'address' => ['required', 'string', 'max:255'],
            'latitude' => ['required', 'numeric', 'between:-90,90'],//Latitude : max/min +90 to -90
            'longitude' => ['required', 'numeric', 'between:-180,180'],//Longitude : max/min +180 to -180
        ]);

        Listing::where('id', $id)->update([
            'list_name' => $request['list_name'],
            'address' => $request['address'],
            'latitude' => $request['latitude'],
            'longitude' => $request['longitude'],
        ]);

        return redirect()->route('listing.index')->with('success', 'Listing updated successfully.');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Listing::destroy($id);
        return redirect()->back()->with('success', 'Listing deleted successfully.');
    }
}

resources/views/listing/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Create Listing') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('listing.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="list_name" class="col-md-4 col-form-label text-md-right">{{ __('List Name') }}</label>

                                <div class="col-md-6">
                                    <input id="list_name" type="text" class="form-control @error('list_name') is-invalid @enderror" name="list_name" value="{{ old('list_name') }}" maxlength="80" required autofocus>

                                    @error('list_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                    <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                                    <div class="col-md-6">
                                        <textarea rows="4" cols="50" id="address" class="form-control @error('address') is-invalid @enderror" name="address" required>{{ old('address') }}</textarea>

                                        @error('address')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="latitude" class="col-md-4 col-form-label text-md-right">{{ __('Latitude') }}</label>

                                    <div class="col-md-6">
                                        <input id="latitude" type="number" step="any" class="form-control @error('latitude') is-invalid @enderror" name="latitude" value="{{ old('latitude') }}" min="-90" max="90" required>

                                        @error('latitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="longitude" class="col-md-4 col-form-label text-md-right">{{ __('Longitude') }}</label>

                                    <div class="col-md-6">
                                        <input id="longitude" type="number" step="any" class="form-control @error('longitude') is-invalid @enderror" name="longitude" value="{{ old('longitude') }}" min="-180" max="180" required>

                                        @error('longitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Add Listing ') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/listing/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('Edit Listing') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('listing.update', $listing->id) }}">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}

                            <div class="form-group row">
                                <label for="list_name" class="col-md-4 col-form-label text-md-right">{{ __('List Name') }}</label>

                                <div class="col-md-6">
                                    <input id="list_name" type="text" class="form-control @error('list_name') is-invalid @enderror" name="list_name" value="{{ old('list_name', $listing->list_name) }}" maxlength="80" required autofocus>

                                    @error('list_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                    <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                                    <div class="col-md-6">
                                        <textarea rows="4" cols="50" id="address" class="form-control @error('address') is-invalid @enderror" name="address" required>{{ old('address', $listing->address) }}</textarea>

                                        @error('address')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="latitude" class="col-md-4 col-form-label text-md-right">{{ __('Latitude') }}</label>

                                    <div class="col-md-6">
                                        <input id="latitude" type="number" step="any" class="form-control @error('latitude') is-invalid @enderror" name="latitude" value="{{ old('latitude', $listing->latitude) }}" min="-90" max="90" required>

                                        @error('latitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                            </div>

                            <div class="form-group row">
                                    <label for="longitude" class="col-md-4 col-form-label text-md-right">{{ __('Longitude') }}</label>

                                    <div class="col-md-6">
                                        <input id="longitude" type="number" step="any" class="form-control @error('longitude') is-invalid @enderror" name="longitude" value="{{ old('longitude', $listing->longitude) }}" min="-180" max="180" required>

                                        @error('longitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/listing/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @if(session()->has('success'))
        <div class="col-md-12">
            <div class="alert alert-success">
                {{ session()->get('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span
                        aria-hidden="true">×</span>
                </button>
            </div>
        </div>
        @endif
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Listing Dashboard</div>
                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <a href="{{route('listing.create')}}" class="btn btn-success float-right mb-3">Create Listing</a>
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">List ID</th>
                                    <th scope="col">List Name</th>
                                    <th scope="col">Address</th>
                                    <th scope="col">Latitude</th>
                                    <th scope="col">Longitude</th>
                                    <th scope="col">Submitter ID</th>
                                    <th scope="col">Date Created</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($listing as $l)
                                <tr>
                                    <th scope="row">
                                        {{(($listing->currentPage()-1) * $listing->perPage()) + $loop->iteration}}</th>
                                    <td>{{$l->id}}</td>
                                    <td>{{$l->list_name}}</td>
                                    <td>
                                        <pre class="prestyle">{{$l->address}}</pre>
                                    </td>
                                    <td>{{$l->latitude}}</td>
                                    <td>{{$l->longitude}}</td>
                                    <td>{{$l->submitter_id}}</td>
                                    <td>{{$l->created_at}}</td>
                                    <td>
                                        <form method="POST" action="{{route('listing.destroy', $l->id)}}">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <a href="{{route('listing.edit', $l->id)}}" class="btn btn-warning">Edit</a>
                                            <button type="submit" class="btn btn-danger pull-right"
                                                onclick="return confirm('Are you sure you want to delete this listing?')">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{$listing->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection